### ISSUE TITLE
Rename repository to "peppy10003.github.io"

### ISSUE THREAD

**Issue by ghost** [peppy10003/Some-Website-shit#6]
# Renaming repository to "peppy10003.github.io" (title)
As title says rename the repository to "peppy10003.github.io" so instead of users having to go to "[https://peppy10003.github.io/My-Website/](https://peppy10003.github.io/My-Website/Template.html)" they can go to "[https://peppy10003.github.io](https://peppy10003.github.io/My-Website/Template.html)"! This would make accessing the website easier and seem less sketchy as the "/My-Website/Template.html" ending looks weird.

**Comment by colsak** [comment]
I was wrong -_-

**Comment by colsak** [comment]
Now I feel a bit stupid
